const steps = [
    {
        id: 0,
        title: 'Caranguejo',
        description:
            'Voce pode pular se quiser Voce pode pular se quiser Voce pode pular se quiser Voce pode pular se quiser Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-9.svg'),
    },
    {
        id: 1,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-10.svg'),
    },
    {
        id: 2,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-11.svg'),
    },
    {
        id: 3,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-13.svg'),
    },
    {
        id: 4,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-14.svg'),
    },
    {
        id: 5,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-16.svg'),
    },
    {
        id: 6,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-17.svg'),
    },
    {
        id: 7,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-20.svg'),
    },
    {
        id: 8,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-22.svg'),
    },
    {
        id: 9,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-23.svg'),
    },
    {
        id: 10,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-24.svg'),
    },
    {
        id: 11,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-25.svg'),
    },
    {
        id: 12,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-26.svg'),
    },
    {
        id: 13,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-27.svg'),
    },
    {
        id: 14,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-28.svg'),
    },
    {
        id: 15,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-29.svg'),
    },
    {
        id: 16,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-30.svg'),
    },
    {
        id: 17,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-31.svg'),
    },
    {
        id: 18,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-32.svg'),
    },
    {
        id: 19,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-33.svg'),
    },
    {
        id: 20,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-35.svg'),
    },
    {
        id: 21,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-36.svg'),
    },
    {
        id: 22,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-37.svg'),
    },
    {
        id: 23,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-38.svg'),
    },
    {
        id: 24,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-39.svg'),
    },
    {
        id: 25,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-40.svg'),
    },
    {
        id: 26,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-41.svg'),
    },
    {
        id: 27,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-42.svg'),
    },
    {
        id: 28,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-43.svg'),
    },
    {
        id: 29,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-44.svg'),
    },
    {
        id: 30,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-46.svg'),
    },
    {
        id: 31,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-47.svg'),
    },
    {
        id: 32,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-56.svg'),
    },
    {
        id: 33,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-57.svg'),
    },
    {
        id: 34,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-58.svg'),
    },
    {
        id: 35,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-59.svg'),
    },
    {
        id: 36,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-60.svg'),
    },
    {
        id: 37,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-61.svg'),
    },
    {
        id: 38,
        title: 'Caranguejo',
        description: 'Voce pode pular se quiser',
        image: require('./Static/Positions/ks-position-62.svg'),
    },
];

export default steps;
